### ISSUE TITLE
'uniq' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by nthsense** [simonrenoult/code-complexity#13]
I'm running this on Windows 10, both CMD and Powershell - looks like there is a dependency on something I don't have.

`Error: Command failed: git -C ./ log --follow --format='' --name-only '*' | sort | uniq -c
'uniq' is not recognized as an internal or external command,
operable program or batch file.
fatal: invalid --pretty format: ''`

**Comment by victoriaunizhona** [comment]
The same issue for me. Have you found a solution?

If I run from Bash - it gives only  invalid --pretty format: ''

**Comment by rluvaton** [comment]
> I'm running this on Windows 10, both CMD and Powershell - looks like there is a dependency on something I don't have.
> 
> `Error: Command failed: git -C ./ log --follow --format='' --name-only '*' | sort | uniq -c 'uniq' is not recognized as an internal or external command, operable program or batch file. fatal: invalid --pretty format: ''`

Testing on Windows 10 in CMD, PowerShell, and Git Bash the error I get is only:
```console
$ code-complexity . --limit 20 --sort ratio
fatal: invalid --pretty format: ''
┌──────┬────────────┬───────┬───────┐
│ file │ complexity │ churn │ ratio │
└──────┴────────────┴───────┴───────┘
```

**Comment by rluvaton** [comment]
@victoriaunizhona @nthsense I found the bug, I'll create a PR in a few minutes
