### ISSUE TITLE
Example for applying multiple filters is incorrect

### ISSUE THREAD

**Issue by bolatovumar** [simonrenoult/code-complexity#16]
README file shows this as an example for applying multiple filters:

```sh
$ code-complexity <dir> --filter 'src/**','!src/front'
```

This doesn't seem to actually work. I think it should be `$ code-complexity <dir> --filter 'src/**, !src/front'` instead as that seems to work.

**Comment by simonrenoult** [comment]
Hi,

Indeed! I answered in your PR :)
