### ISSUE TITLE
Why is it called “ratio” instead of “product”?

### ISSUE THREAD

**Issue by pmcelhaney** [simonrenoult/code-complexity#18]
Since churn is multiplied by complexity, shouldn't the result be the **product** of churn and complexity? If we were dividing churn by complexity, the result would be the ratio of churn to complexity. 

Let me know if I'm missing something. Otherwise I'm happy to create a PR. :)

**Comment by simonrenoult** [comment]
Hi @pmcelhaney, thanks for the feedback!

When I designed the lib, I considered the multiplication as an implementation detail. Meaning that it doesn't really matter if the ratio is computed from a complex or a simple equation, what matters is that the ratios are consistent and can be compared. Hence why I don't use the mathematical term to describe the link between churn and complexity. 

Here, "ratio" is used as a synonym of "proportion" (source: source: https://www.thesaurus.com/browse/ratio). 

I'm not a native English speaker though. Do you think another word could convey a more accurate meaning? Or should I explain this somewhere?

**Comment by pmcelhaney** [comment]
Ah, that makes sense. If x = y/z, then x is a ratio. If x = y * z, then x is a product. If x = y^x - 2z + 1, then x is... I'm not sure. Mathematicians probably have a word for it.  :)

The most idiomatic word that comes to mind in this context is "score". In a football match, an entrance exam, or a video game, we use some formula to compute a number, and use that number to determine ranking. The highest score isn't necessarily the best. In golf, for example, the lowest score wins.

**Comment by simonrenoult** [comment]
> Ah, that makes sense. If x = y/z, then x is a ratio. If x = y * z, then x is a product. If x = y^x - 2z + 1, then x is... I'm not sure. Mathematicians probably have a word for it. :)

Exactly :smile: 

> The most idiomatic word that comes to mind in this context is "score". In a football match, an entrance exam, or a video game, we use some formula to compute a number, and use that number to determine ranking. The highest score isn't necessarily the best. In golf, for example, the lowest score wins.

"score" sounds good to me! Could you open a PR and make the change? :eyes:
