### ISSUE TITLE
Add a way to compute complexity based on something else than sloc

### ISSUE THREAD

**Issue by simonrenoult** [simonrenoult/code-complexity#5]
#### What problem are you trying to solve?

We're currently measuring complexity based on `sloc`. It's nice but a long file doesn't always mean it's complex.

#### Describe the feature

We could add a `--complexity-strategy=<sloc or cyclomatic or xyz>` that would be used in the complexity processing.

**Comment by davemcg3** [comment]
The algorithm just counts lines of code and returns that as complexity then? Would be good to have that in the readme. Looks like it comes from here:
`const result = await nodeSloc({ path: absolutePath });`
Can open a PR for the README adjustment if you will confirm.

**Comment by davemcg3** [comment]
Added PR to cover the above:
https://github.com/simonrenoult/code-complexity/pull/24

**Comment by simonrenoult** [comment]
Seems fair. I changed the wording a bit and merged it, thanks :+1:

**Comment by simonrenoult** [comment]
Candidates:

- https://www.npmjs.com/package/escomplex
- https://eslint.org/docs/rules/complexity and its source https://github.com/eslint/eslint/blob/master/lib/rules/complexity.js

**Comment by scottamplitude** [comment]
Added PR to cover the requested functionality:
#28
This library will then support the following complexity strategies:

- SLOC
- Cyclomatic
- Halstead

Code adapted from:
https://github.com/anandundavia/ts-complex
