### ISSUE TITLE
Move away from node-sloc

### ISSUE THREAD

**Issue by simonrenoult** [simonrenoult/code-complexity#6]
#### What problem are you trying to solve?

Not really a feature but we depend on `node-sloc` to count file complexity. Which is far from being popular and is at risk of being abandoned one day.

#### Describe the feature

We should look into alternatives.

**Comment by eshimischi** [comment]
Not much alternatives, but [scnt](https://github.com/chris-pikul/scnt)

**Comment by simonrenoult** [comment]
In the end, we'll keep node-sloc for simplicity sake and fallback to a manual line count when node-sloc does not support the file type.
