### ISSUE TITLE
Accuracy for Sass files

### ISSUE THREAD

**Issue by pdewouters** [simonrenoult/code-complexity#9]
Apologies for creating an issue, I couldn't find any contact details. Thanks for writing this tool,I was wondering if it can give accurate results for Sass/SCSS files? How is the complexity calculated in a language agnostic manner? 
Thanks

I get this message BTW: `warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your diff.renameLimit variable to at least 755 and retry the command.`

**Comment by simonrenoult** [comment]
Hi,

Sorry for the late answer. Providing more accurate complexity for SASS is currently quite complicated since it requires a better approach to complexity calculation than the current one. I'm looking into it but it won't land any time soon, sorry.

**Comment by pdewouters** [comment]
thanks, will do
